apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Programador\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: jupyter
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jupyter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Programador\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/project-2-default: "true"
        io.kompose.service: jupyter
    spec:
      containers:
        - env:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
          image: jupyter
          name: jupyter
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /work
              name: jupyter-claim0
      restartPolicy: Always
      volumes:
        - name: jupyter-claim0
          persistentVolumeClaim:
            claimName: jupyter-claim0
status: {}
